method: cmaes  # Covariance matrix adaptation.

out_dir: './experiments/synthetic_experiments/test/cmaes_optimize/'

# Either choose max_iterations or max_objective_calls not None.
max_iterations: 
max_objective_calls: 200

optimizer_config:
    sigma: 0.5  # 0.3*get_lengthscales(dim, factor_hennig) 
