out_dir : './experiments/synthetic_experiments/test/'
dimensions : [4, 8, 12, 20, 32, 52]
num_objectives : 100
num_samples : 1000
noise_variance : 0.01
factor_lengthscale : 2
gamma : 0.3
gp_hypers: 
    outputscale: 1.
gp_hypers_IS:
    outputscale: 0.2
n_max: 15
