method: s-hci-gibo

out_dir: './experiments/synthetic_experiments/test/S-HCI-GIBO-optimize/'

# Either choose max_iterations or max_objective_calls not None.
max_iterations:
max_objective_calls: 200

# Manually set hyperparameters.
set_hypers: False  
only_set_noise_hyper: False 

optimizer_config: 
    max_samples_per_iteration: dim_search_space
    OptimizerTorch: sgd
    optimizer_torch_config: 
        lr: 0.25
    lr_schedular:
    alpha: 0.95
    Model: derivative_gp_IS
    model_config:
        prior_mean: 0.
        ard_num_dims: dim_search_space  # If not None, each input dimension gets its own separate lengthscale.
        N_max: variable  # 5*dim_search_space
        lengthscale_constraint: 
            constraint:
            kwargs:
        lengthscale_hyperprior: 
            prior: normal 
            kwargs:
                loc: 0.3
                scale: 0.15
        outputscale_constraint:
            constraint: 
            kwargs: 
        outputscale_hyperprior:
            prior: 
            kwargs:
        lengthscale_constraint_IS:
            constraint:
            kwargs:
        lengthscale_hyperprior_IS:
            prior: normal
            kwargs:
                loc: 0.2
                scale: 0.15
        outputscale_constraint_IS:
            constraint:
            kwargs:
        outputscale_hyperprior_IS:
            prior: normal
            kwargs:
                loc: 0.2
                scale: 0.1
        noise_constraint: 
            constraint:
            kwargs:
        noise_hyperprior:
            prior: 
            kwargs:
                loc: 
                scale:
    hyperparameter_config: 
        optimize_hyperparameters: True
        hypers:
            covar_module.base_kernel.lengthscale: 0.60
            covar_module.outputscale: 1
            likelihood.noise: 0.01
            covar_module_IS.base_kernel.lengthscale: 0.60
            covar_module_IS.outputscale: 0.2
        no_noise_optimization: True
    optimize_acqf: bga-IS
    optimize_acqf_config: 
        q: 1
        num_restarts: 5
        raw_samples: 64
    # Either choose bounds or delta unequal None.
    bounds: 
        lower_bound: 0.0
        upper_bound: 1.0
    delta: 0.1
    epsilon_diff_acq_value: 1
    generate_initial_data:
    standard_deviation_scaling: False
    normalize_gradient: True
    verbose: True
